[package]
name = "pv-simulator"
version = "0.1.0"
edition = "2021"
authors = ["Aleks Pickle <aleks.work2222@gmail.com>"]

[dependencies]
anyhow = "1.0"
deadpool-lapin = "0.10"
lapin = "2.1.1"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "*"
futures-lite = "*"

